version: '3.8'

services:
  apk-protection:
    build: .
    container_name: apk-protection-service
    ports:
      - "5000:5000"
    volumes:
      - ./temp:/app/temp
      - ./logs:/app/logs
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
